# -*- coding: utf-8 -*-
import os.path

# Form implementation generated from reading ui file 'Insert.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from choose import choose_file
import QT_PLUGIN_PATH_INSERT, functools

NewApp: tuple = ()
AppPath: dict = {}


class Ui_Dialog(object):
    def setupUi(self, Dialog, AppPath: dict, window_type: str = 'insert', *, text1: str = None, text2: str = None):
        self.AppPath = AppPath
        Dialog.setObjectName("Dialog")
        Dialog.resize(602, 97)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 50, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 61, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 50, 291, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 61, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(110, 10, 371, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(500, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 30, 291, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(110, 70, 291, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton_3.clicked.connect(self.view)  # type: ignore

        self.lineEdit.textChanged.connect(self.text_changed1)
        self.lineEdit_2.textChanged.connect(self.text_changed2)

        if window_type == 'edit':
            self.lineEdit.setText(text1)
            self.lineEdit_2.setText(text2)

        self.OK = functools.partial(self.OK, window = Dialog, window_type=window_type, text1=text1, text2=text2)

        self.pushButton.clicked.connect(self.OK)  # type: ignore

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_3.setText(_translate("Dialog", "浏览"))
        self.pushButton_3.setShortcut(_translate("Dialog", "V"))
        self.label_2.setText(_translate("Dialog", "应用路径:"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "请输入应用路径"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.pushButton_2.setShortcut(_translate("Dialog", "C"))
        self.label.setText(_translate("Dialog", "应用名:"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "请输入应用名"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.pushButton.setShortcut(_translate("Dialog", "O"))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
        self.label_4.setText(_translate("Dialog", "TextLabel"))

        self.label_3.hide()
        self.label_4.hide()
        self.label_3.setStyleSheet('color:red;')
        self.label_4.setStyleSheet('color:red;')

    def text_changed1(self):
        self.label_3.hide()

    def text_changed2(self):
        self.label_4.hide()

    def view(self):
        if choose := choose_file([('可执行文件', '*.bat;*.exe'), ('所有文件', '*.*')]):
            self.lineEdit_2.setText(choose)

    def OK(self, window, window_type: str = 'insert', *, text1: str = None, text2: str = None):
        error = False

        if not self.lineEdit.text():
            self.change_text1('此栏不为空!')
            error = True
        if not self.lineEdit_2.text():
            self.change_text2('此栏不为空!')
            error = True
        elif not os.path.exists(self.lineEdit_2.text()):
            self.change_text2('路径无效!')
            error = True
        if all((self.lineEdit.text() == text1, self.lineEdit_2.text() == text2, window_type == 'edit')):
            self.change_text1('未更改!')
            self.change_text2('未更改!')
            error = True
        if all((self.lineEdit.text() in self.AppPath.keys(), window_type == 'insert')):
            self.change_text1('应用名已存在!')
            error = True
        if not error:
            self.result_data = {'InitialName': text1, 'InitialPath': text2, 'Name': self.lineEdit.text(), 'Path': self.lineEdit_2.text()}
            window.accept()

    def change_text1(self, text: str):
        self.label_3.setText(text)
        self.label_3.show()

    def change_text2(self, text: str):
        self.label_4.setText(text)
        self.label_4.show()

class a(Ui_Dialog):
    def OK(self, window, *args, **kwargs):
        dialog.accepted('6')
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = a()
    ui.setupUi(dialog, AppPath)
    dialog.show()
    print(dialog.accepted)
    sys.exit(app.exec_())
