# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 393)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 30, 391, 251))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 40, 107, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 90, 107, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 140, 107, 23))
        self.pushButton_6.setMouseTracking(False)
        self.pushButton_6.setAcceptDrops(False)
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(450, 190, 107, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 320, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(30, 290, 391, 16))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(450, 240, 107, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 310, 391, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_4.clicked.connect(self.open)
        self.pushButton_5.clicked.connect(self.insert)
        self.pushButton_6.clicked.connect(self.delete)
        self.pushButton_7.clicked.connect(self.edit)
        self.listWidget.itemClicked.connect(self.choose)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "app1"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "app2"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_4.setText(_translate("MainWindow", "Open"))
        self.pushButton_4.setShortcut(_translate("MainWindow", "O"))
        self.pushButton_5.setText(_translate("MainWindow", "Insert"))
        self.pushButton_5.setShortcut(_translate("MainWindow", "I"))
        self.pushButton_6.setText(_translate("MainWindow", "Delete"))
        self.pushButton_6.setShortcut(_translate("MainWindow", "D"))
        self.pushButton_7.setText(_translate("MainWindow", "Edit"))
        self.pushButton_7.setShortcut(_translate("MainWindow", "E"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))
        self.pushButton_2.setShortcut(_translate("MainWindow", "Esc"))
        self.checkBox.setText(_translate("MainWindow", "打开应用后不关闭此窗口"))
        self.pushButton_8.setText(_translate("MainWindow", "Link"))
        self.pushButton_8.setShortcut(_translate("MainWindow", "L"))
        self.checkBox_2.setText(_translate("MainWindow", "不确认删除"))

        self.pushButton_4.setEnabled(False)
        self.pushButton_6.setEnabled(False)
        self.pushButton_7.setEnabled(False)
        self.pushButton_8.setEnabled(False)

    def choose(self):
        self.pushButton_4.setEnabled(True)
        self.pushButton_6.setEnabled(True)
        self.pushButton_7.setEnabled(True)
        self.pushButton_8.setEnabled(True)

    def settings(self):
        print('settings')

    def open(self):
        print(self.listWidget.currentItem().text())
        if not self.checkBox.isChecked():
            MainWindow.close()

    def insert(self):
        print('insert')

    def delete(self):
        self.listWidget.takeItem(self.listWidget.currentRow())

    def edit(self):
        print('edit')

    def add_choice_to_viewlist(self, AppDict: dict[str, AppDir]):
        self.listWidget.addItems(AppDict.keys())
