# -*- coding: utf-8 -*-


# Form implementation generated from reading ui file 'UI_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Um(object):
    def setupUi(self, MainWindow, text='提示信息', title='提示'):
        ''':param text:请使用markdown文本
        :param title:窗口标题
        :return (bool, bool)'''
        self.mainwindow = MainWindow
        self.returndata = None
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(333, 187)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 301, 91))
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 130, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(60, 90, 211, 20))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow, text, title)
        self.pushButton.clicked.connect(self.OK)  # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, text='提示信息', title='提示'):
        ''':param text:请使用markdown文本
        :param title:窗口标题'''
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", title))
        self.label.setText(_translate("MainWindow", text))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.pushButton.setShortcut(_translate("MainWindow", "O"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_2.setShortcut(_translate("MainWindow", "C"))
        self.checkBox.setText(_translate("MainWindow", "下次不再提示"))

    def OK(self):
        self.returndata = (self.checkBox.isChecked(), True)
        self.mainwindow.close()


if __name__ == '__main__':
    import QT_PLUGIN_PATH_INSERT, sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Um()
    ui.setupUi(MainWindow, '## 确认删除？', '提示')
    MainWindow.show()
    app.exec()
    print(ui.returndata)
