# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UM.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QDialog):
    def setupUi(self, Dialog):
        self.mainwindow = Dialog
        self.returndata = None
        Dialog.setObjectName("Dialog")
        Dialog.resize(329, 190)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 301, 91))
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 130, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 130, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(60, 100, 211, 20))
        self.checkBox_2.setObjectName("checkBox_2")

        self.retranslateUi(Dialog)
        self.pushButton_3.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "**确定删除？**"))
        self.pushButton_4.setText(_translate("Dialog", "OK"))
        self.pushButton_4.setShortcut(_translate("Dialog", "O"))
        self.pushButton_3.setText(_translate("Dialog", "Cancel"))
        self.pushButton_3.setShortcut(_translate("Dialog", "C"))
        self.checkBox_2.setText(_translate("Dialog", "下次不再提示"))

    def OK(self):
        self.returndata = (self.checkBox_2.isChecked(), True)
        self.mainwindow.close()
