# -*- coding: utf-8 -*-


#
# Form implementation generated from reading ui file 'apps_launcher_v2.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

choice = ''
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(280, 165)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 40, 221, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.buttonBox_Open = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox_Open.setGeometry(QtCore.QRect(40, 90, 71, 23))
        self.buttonBox_Open.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.buttonBox_Open.setCenterButtons(False)
        self.buttonBox_Open.setObjectName("buttonBox_Open")
        self.buttonBox_Cancel = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox_Cancel.setGeometry(QtCore.QRect(160, 90, 71, 23))
        self.buttonBox_Cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox_Cancel.setObjectName("buttonBox_Cancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 280, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setTitle("")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.retranslateUi(MainWindow)
        self.buttonBox_Cancel.clicked['QAbstractButton*'].connect(MainWindow.close) # type: ignore
        self.buttonBox_Open.clicked['QAbstractButton*'].connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "选择想打开的应用"))

    def add_choices(self,choice:list):
        '''添加选项'''
        for x in choice:
            self.comboBox.addItem(x)

    def get_choice(self):
        '''获取选项'''
        return self.comboBox.currentText()


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

    def closeEvent(self, event):
        """重写关闭事件，在窗口关闭前执行"""
        global choice
        choice = self.ui.get_choice()
        print(f"关闭前选择的选项是: {choice}")
        event.accept()                ### 接受关闭事件


if __name__ == '__main__':
    import sys, QT_PLUGIN_PATH_INSERT
    app=QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.ui.add_choices(['666'])                    ###添加选项
    window.setWindowTitle('应用启动器v2.0')
    window.show()
    sys.exit(app.exec_())


'''
有警告
用json写入和读取文件
'''
